// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJmPbgEnN-x_yqIS9ClkJMhIOWmUdaw3Y',
    appId: '1:362318855645:web:a4dcda7bedaae9661b4a34',
    messagingSenderId: '362318855645',
    projectId: 'chat-app-707f8',
    authDomain: 'chat-app-707f8.firebaseapp.com',
    storageBucket: 'chat-app-707f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuRuVtjZ0zUPJLoA55HiGLJNNrAnvBFKM',
    appId: '1:362318855645:android:b46c8c17595963fc1b4a34',
    messagingSenderId: '362318855645',
    projectId: 'chat-app-707f8',
    storageBucket: 'chat-app-707f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlAouvb9gsYBPsxHJnHqhNjgqVTuWllOk',
    appId: '1:362318855645:ios:61a4b1473519f6ee1b4a34',
    messagingSenderId: '362318855645',
    projectId: 'chat-app-707f8',
    storageBucket: 'chat-app-707f8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}